const DB = {
    "animais": [
        {"nome": "Abrigo Animal Joinville",
         "texto": "Torne-se padrinho ou madrinha de um cão idoso de nosso abrigo!",
         "views": 123, "data": new Date("2020-05-23"), "tipo": "org"},
        {"nome": "Amiva",
         "texto": "Educar os humanos para posse responsável de animais e promover adoção de cães e gatos.",
         "views": 43, "data": new Date("2020-04-19"), "tipo": "org"},
        {"nome": "Arca",
         "texto": "Em 25 anos de atuação, os projetos, eventos e outras ações da ARCA BRASIL, trazem esperança aos direitos dos animais no país.",
         "views": 235, "data": new Date("2019-03-18"), "tipo": "org"},
        {"nome": "Arca",
         "texto": "Profissionais que contribuem para a redução do sofrimento animal, sempre dentro de suas possibilidades pessoais e operacionais.",
         "views": 34, "data": new Date("2020-07-07"), "tipo": "evento"},
        {"nome": "Juntos Pelos Animais",
         "texto": "Evento para arrecadação de ração para nosso abrigo. Venham!",
         "views": 12, "data": new Date("2020-06-18"), "tipo": "evento"},
        {"nome": "Defesa Animal",
         "texto": "Nosso objetivo é proteger animais em situação de vulnerabilidade, vítimas de abandono, atropelamentos e maus tratos.",
         "views": 124, "data": new Date("2020-01-03"), "tipo": "org"},
        {"nome": "Prefeitura de São Paulo",
         "texto": "Ajuda para encontrar animais desaparecidos",
         "views": 68, "data": new Date("2020-04-04"), "tipo": "org"},
        {"nome": "Edmilson Andrade",
         "texto": "Estou com alguns cachorros na minha casa que estão procurando por um lar.",
         "views": 12, "data": new Date("2020-04-06"), "tipo": "pessoa"},
        {"nome": "WWF",
         "texto": "O WWF trabalha na região amazônica junto com comunidades locais, indígenas e ongs, para contribuir para a proteção da Amazônia.",
         "views": 234, "data": new Date("2019-10-17"), "tipo": "org"}
    ],
    "meio-ambiente": [
        {"nome": "Favela Verde",
        "texto": "Realizamos projetos socioambientais através de participação e inovação social, que buscam a sustentabilidade urbana.",
        "views": 56, "data": new Date("2019-11-11"), "tipo": "org"},
        {"nome": "Greenpeace",
        "texto": "Chega de destruição da Amazônia! Ajude a frear o desmatamento da nossa floresta.",
        "views": 432, "data": new Date("2020-10-23"), "tipo": "org"},
        {"nome": "Observatório do Clima",
        "texto": "O Observatório do Clima reúne entidades da sociedade civil objetivando discutir a questão das mudanças climáticas no Brasil.",
        "views": 154, "data": new Date("2019-09-17"), "tipo": "org"},
        {"nome": "SOS Mata Atlântica",
        "texto": "Inspirar a sociedade na defesa da Mata Atlântica. Venha conhecer nosso trabalho!",
        "views": 116, "data": new Date("2019-09-19"), "tipo": "org"}
    ],
    "idosos": [
        {"nome": "Ativa Idade",
        "texto": "Somos a ong Ativa Idade, apelidada carinhosamente como ATI, que tem como objetivo proteger o direito dos nossos idosos.",
        "views": 59, "data": new Date("2020-03-23"), "tipo": "org"},
        {"nome": "Ação Social Recreio",
        "texto": "Neste mês de maio doe fraldas geriátricas e infantis para asilos e famílias assistidas pelo nosso programa.",
        "views": 43, "data": new Date("2020-06-06"), "tipo": "evento"},
        {"nome": "Idoso Amado",
        "texto": "Chamando colaboradores que se sensibilizam com a esta causa e querem ajudar de acordo com o que lhes é possível.",
        "views": 49, "data": new Date("2020-04-07"), "tipo": "org"},
        {"nome": "Prefeitura de Trombudo Central",
        "texto": "O evento terá uma tarde com programação especial para a terceira idade.",
        "views": 23, "data": new Date("2020-09-07"), "tipo": "evento"}
    ],
    "deficientes": [
        {"nome": "AACD",
        "texto": "O atendimento que a AACD oferece a milhares de pessoas só é possível graças ao apoio dos nossos colaboradores.",
        "views": 452, "data": new Date("2019-06-23"), "tipo": "org"},
        {"nome": "Adapt Surf",
        "texto": "Divulgar o surf adaptado para pessoas com deficiência, preservar a Natureza e lutar por mais acessibilidade nas praias.",
        "views": 165, "data": new Date("2019-09-24"), "tipo": "org"},
        {"nome": "Adapt Surf",
        "texto": "Venha participar do evento de surf no dia Internacional da pessoa com deficiência.",
        "views": 59, "data": new Date("2020-06-18"), "tipo": "evento"},
        {"nome": "APAE",
        "texto": "Sua doação é fundamental para continuidade dos trabalhos desenvolvidos pelas Apaes.",
        "views": 79, "data": new Date("2020-02-19"), "tipo": "org"},
        {"nome": "Vicente Domingos",
        "texto": "Sou paraplégico e estou precisando de uma cadeira de rodas, pois a minha quebrou. Moro em pirituba.",
        "views": 23, "data": new Date("2020-02-19"), "tipo": "pessoa"}
    ],
    "educacao": [
        {"nome": "Ciranda do Saber",
        "texto": "A Ciranda do Saber realiza a fomentação da leitura através da destinação de livros a ONGs e eventos literários.",
        "views": 165, "data": new Date("2019-07-23"), "tipo": "org"},
        {"nome": "CPM",
        "texto": "Oferecemos cursos de inglês para jovens e adultos de comunidades carentes promovendo a inserção e integração social.",
        "views": 173, "data": new Date("2019-09-14"), "tipo": "org"},
        {"nome": "IOS",
        "texto": "Apoiar e monitorar a empregabilidade de jovens e pessoas com deficiência, que tenham menor acesso ao mercado de trabalho.",
        "views": 124, "data": new Date("2020-02-07"), "tipo": "org"},
        {"nome": "Jovens Hackers",
        "texto": "Empoderamos crianças e adolescentes em situação de vulnerabilidade social por meio da tecnologia, com aulas a baixo custo.",
        "views": 97, "data": new Date("2020-04-09"), "tipo": "org"},
        {"nome": "Guri",
        "texto": "O ensino musical é a ferramenta escolhida pelo Projeto Guri para o cumprimento da sua missão de inclusão sociocultural.",
        "views": 202, "data": new Date("2019-09-18"), "tipo": "org"},
        {"nome": "PyLadies",
        "texto": "O PyLadies é uma comunidade mundial que foi trazida ao Brasil com o propósito de trazer mais mulheres para a área tecnológica.",
        "views": 201, "data": new Date("2020-02-07"), "tipo": "org"},
        {"nome": "PyLadies",
        "texto": "Abordaremos tópicos de estatística descritiva e como aplicá-los em análises de dados usando Python, com Pandas e Seaborn.",
        "views": 76, "data": new Date("2020-05-23"), "tipo": "evento"},
        {"nome": "Todos pela Educação",
        "texto": "Nosso propósito é melhorar o Brasil, impulsionando a qualidade e a equidade da Educação Básica no País.",
        "views": 75, "data": new Date("2020-03-24"), "tipo": "org"}
    ],
    "alimentacao": [
        {"nome": "Armazém do Campo",
        "texto": "Produtos agroecológicos, orgânicos e da agricultura familiar. Venha e traga sua famíliapara conhecer um novo jeito de comer bem.",
        "views": 87, "data": new Date("2020-02-21"), "tipo": "org"},
        {"nome": "Armazém do Campo",
        "texto": "Feira Nacional da Reforma Agrária 2020. Confira o que vai rolar nesta edição!",
        "views": 48, "data": new Date("2020-12-20"), "tipo": "evento"},
        {"nome": "Sopão Solidário",
        "texto": "Venha contribuir com o sopão comunitário durante esse inverno!",
        "views": 45, "data": new Date("2020-07-12"), "tipo": "evento"},
        {"nome": "Banco de Alimentos",
        "texto": "Buscamos alimentos onde sobra e levamos onde falta.",
        "views": 76, "data": new Date("2020-05-31"), "tipo": "org"},
        {"nome": "Stop Hunger",
        "texto": "Junte-se a nós! Doe cestas básica durante a restrição do covid-19.",
        "views": 120, "data": new Date("2019-12-07"), "tipo": "org"},
        {"nome": "Horta na Laje",
        "texto": "O Horta na Laje tem como objetivo incentivar a alimentação saudável, a sustentabilidade e a economia dentro de Paraisópolis.",
        "views": 79, "data": new Date("2020-03-09"), "tipo": "org"}
    ],
    "moradia": [
        {"nome": "Anjos da Noite",
        "texto": "Manter o corpo aquecido é essencial. Todos precisamos de cobertores em qualquer época do ano e principalmente no inverno.",
        "views": 42, "data": new Date("2020-06-13"), "tipo": "evento"},
        {"nome": "Banco da Providência",
        "texto": "O Banco da Providência desenvolve projetos de inclusão social para jovens, adultos e famílias em pobreza extrema no RJ.",
        "views": 76, "data": new Date("2020-04-30"), "tipo": "org"},
        {"nome": "Habitat",
        "texto": "Incentivar as pessoas a construírem juntas casas, comunidades e esperança, procurando assim transformar o amor de Deus em ação.",
        "views": 56, "data": new Date("2019-10-19"), "tipo": "org"},
        {"nome": "Teto",
        "texto": "Superar a situação de pobreza em que vivem milhões de pessoas nas comunidades precárias, junto aos moradores e voluntários.",
        "views": 234, "data": new Date("2019-05-24"), "tipo": "org"}
    ],
    "refugiados": [
        {"nome": "ACNUR",
        "texto": "Trabalhamos para oferecer proteção, acesso à educação e assistência médica aos refugiados no Brasil e no mundo.",
        "views": 176, "data": new Date("2019-07-16"), "tipo": "org"},
        {"nome": "ADUS",
        "texto": "O Adus oferece para os refugiados aulas de português, inserção no mercado de trabalho e orientação jurídica.",
        "views": 78, "data": new Date("2020-02-19"), "tipo": "org"},
        {"nome": "Migraflix",
        "texto": "Apostamos no conhecimento dos refugiados, ajudando em projetos que geram renda, para possibilitar uma vida mais digna em nosso país.",
        "views": 74, "data": new Date("2020-02-08"), "tipo": "org"}
    ]
}